const CONFIG_CACHE="scout-push-config-v1";
const CONFIG_URL=new URL("__scout_push_config__",self.registration.scope).href;
self.addEventListener("install",event=>event.waitUntil(self.skipWaiting()));
self.addEventListener("activate",event=>event.waitUntil(clients.claim()));
async function saveConfig(value){const cache=await caches.open(CONFIG_CACHE);await cache.put(CONFIG_URL,new Response(JSON.stringify(value),{headers:{"Content-Type":"application/json"}}));}
async function readConfig(){const cache=await caches.open(CONFIG_CACHE);const res=await cache.match(CONFIG_URL);if(!res)return null;return res.json().catch(()=>null);}
self.addEventListener("message",event=>{if(event.data?.type==="SCOUT_PUSH_CONFIG"&&event.data?.endpoint&&event.data?.token)event.waitUntil(saveConfig({endpoint:String(event.data.endpoint),token:String(event.data.token)}));});
self.addEventListener("push",event=>{event.waitUntil((async()=>{let title="HOF Card Scout",body="Scout completed an automated marketplace search. Open the app for details.",id=String(Date.now());try{const cfg=await readConfig();if(cfg?.endpoint&&cfg?.token){const res=await fetch(cfg.endpoint+"/push/latest?token="+encodeURIComponent(cfg.token));const data=await res.json().catch(()=>({}));if(res.ok&&data.ok){title=data.title||title;body=data.body||body;id=data.id||id;}}}catch{}const target=new URL("./?automation=1",self.registration.scope);target.searchParams.set("push",String(id));target.searchParams.set("notice",String(Date.now()));await self.registration.showNotification(title,{body,icon:new URL("icon-180.png",self.registration.scope).href,badge:new URL("icon-180.png",self.registration.scope).href,tag:"scout-automation-"+id,data:{url:target.href,pushId:String(id)}});})());});
self.addEventListener("notificationclick",event=>{event.notification.close();event.waitUntil((async()=>{const pushId=String(event.notification.data?.pushId||"");const target=event.notification.data?.url||new URL("./?automation=1",self.registration.scope).href;const rows=await clients.matchAll({type:"window",includeUncontrolled:true});for(const client of rows){if(!client.url.startsWith(self.registration.scope))continue;if(client.visibilityState==="visible"){client.postMessage({type:"OPEN_AUTOMATION",pushId});return client.focus();}try{const navigated=await client.navigate(target);return navigated?await navigated.focus():await client.focus();}catch{client.postMessage({type:"OPEN_AUTOMATION",pushId});return client.focus();}}return clients.openWindow(target);})());});
