const assert=require("node:assert/strict");
const fs=require("node:fs");
const html=fs.readFileSync("index.html","utf8");
assert.match(html,/Hunt List 2\.0/);
assert.match(html,/id="huntActiveCount"/);
assert.match(html,/data-hunt-filter="all"/);
assert.match(html,/let huntFilter="all"/);
assert.match(html,/function huntTargetPlayers\(\)\{return PLAYERS\.filter\(p=>!!p\.target&&!p\.incoming\)/);
assert.match(html,/🎯 READY TO HUNT/);
assert.match(html,/✕ OPEN ROSTER SPOTS/);
assert.match(html,/📦 ON THE WAY/);
assert.match(html,/data-hunt-action="findtarget"/);
assert.match(html,/data-hunt-action="edit"/);
assert.match(html,/data-hunt-action="received"/);
assert.match(html,/data-future-hunt-action="edit"/);
assert.match(html,/data-future-hunt-action="remove"/);
assert.match(html,/targetListingUrl/);
assert.match(html,/v5\.2\.0/);
console.log("Hunt List 2.0 tests passed.");
