const assert=require('node:assert/strict');
const fs=require('node:fs');
const worker=fs.readFileSync('src/index.js','utf8');
const ui=fs.readFileSync('push-notifications.js','utf8');
const sw=fs.readFileSync('scout-push-sw.js','utf8');
const html=fs.readFileSync('index.html','utf8');
assert.match(worker,/const VERSION = "3\.34\.0"/);
assert.match(worker,/PUSH_VAPID_KEY = "push:vapid:v1"/);
assert.match(worker,/url\.pathname === "\/push\/config"/);
assert.match(worker,/url\.pathname === "\/push\/subscribe"/);
assert.match(worker,/url\.pathname === "\/push\/test"/);
assert.match(worker,/url\.pathname === "\/push\/latest"/);
assert.match(worker,/crypto\.subtle\.generateKey\(\{ name: "ECDSA", namedCurve: "P-256" \}/,'VAPID key must be generated privately on the Worker');
assert.match(worker,/Authorization.*vapid t=/s,'push sends must use VAPID authorization');
assert.match(worker,/if \(Number\(targetRun\.result\?\.searchUsed\) > 0\)[\s\S]*pushNotifySubscribers/,'scheduled target pushes require a real search');
assert.match(worker,/if \(Number\(collectionRun\.result\?\.searchUsed\) > 0\)[\s\S]*pushNotifySubscribers/,'scheduled collection pushes require a real search');
assert.match(ui,/Notification\.requestPermission\(\)/);
assert.match(ui,/pushManager\.subscribe/);
assert.match(ui,/SEND TEST NOTIFICATION · 0 SEARCHES/);
assert.doesNotMatch(ui,/runEbaySearch\(|c\.endpoint\+"\/value"|api\("\/value"/,'notification setup must not invoke pricing searches');
assert.match(sw,/addEventListener\("push"/);
assert.match(sw,/showNotification/);
assert.match(sw,/\/push\/latest\?token=/);
assert.match(html,/push-notifications\.js/);
console.log('Push notification tests passed.');
