const assert=require('node:assert/strict');
const fs=require('node:fs');
const worker=fs.readFileSync('src/index.js','utf8');
const app=fs.readFileSync('sealed-product-scout.js','utf8');
const wrangler=fs.readFileSync('wrangler.jsonc','utf8');

assert.match(worker,/const VERSION = "3\.38\.1"/);
assert.match(wrangler,/"ai"\s*:\s*\{\s*"binding"\s*:\s*"AI"/s,'Workers AI binding must be configured');
assert.match(worker,/\/sealed\/identify/,'sealed vision endpoint must exist');
assert.match(worker,/\/sealed\/barcode-identify/,'sealed barcode endpoint must exist');
assert.match(worker,/\/sealed\/classify-type/,'sealed product type classifier endpoint must exist');
assert.match(worker,/\/sealed\/value-check/,'sealed market value endpoint must exist');
assert.match(app,/CHECK MARKET VALUE · 1 SEARCH MAX/,'sealed scanner must expose the one-search market check');
assert.match(app,/sealed\/value-check/,'front end must call the sealed market endpoint');
assert.match(app,/rawField=byId\(\"sealedShelfPrice\"\)/,'market check must read the currently entered shelf price');
assert.match(app,/saveDraft\(\{shelfPrice,store:/,'market check must auto-save the entered shelf price');
assert.match(worker,/engine\", \"ebay/,'sealed market check must use the eBay search engine');
assert.ok(worker.includes('rip\\s*(?:&|and)\\s*ship'),'sealed market check must reject rip-and-ship listings');
assert.match(app,/TAKE FRONT PHOTO FOR PRODUCT TYPE/,'barcode-confirmed products should request a front photo when type is missing');
assert.match(app,/sealed\/classify-type/,'front end must call the narrow product type classifier');
assert.match(app,/classifyProductTypeFromPhoto/,'front end should classify only package type after barcode identity');
assert.match(worker,/api\.upcitemdb\.com\/prod\/trial\/lookup/,'barcode lookup should use the free UPC database endpoint');
assert.match(app,/SCAN BARCODE/,'sealed scanner must expose barcode photo capture');
assert.match(app,/BarcodeDetector/,'browser-native barcode detection should be attempted when supported');
assert.match(app,/sealed\/barcode-identify/,'barcode UI must call the Scout barcode endpoint');
assert.match(worker,/@cf\/moondream\/moondream3\.1-9B-A2B/,'Cloudflare-hosted vision model must be used');
assert.match(worker,/raw\?\.answer/,'Moondream query answer envelope must be parsed');
assert.match(worker,/stream:\s*false/,'Moondream query must use non-streaming output for deterministic parsing');
assert.match(worker,/marketplaceSearchesUsed:\s*0/,'vision endpoint must explicitly report zero marketplace searches');
const start=worker.indexOf('url.pathname === "/sealed/identify"');
const end=worker.indexOf('url.pathname === "/automation/status"',start);
const route=worker.slice(start,end);
assert.ok(start>=0&&end>start,'sealed route should be isolated before automation route');
assert.doesNotMatch(route,/SERPAPI_KEY|runEbaySearch|serpapi\.com|APIFY_TOKEN|CARD_API_KEY/i,'vision route must not call marketplace providers');
assert.match(app,/IDENTIFY PRODUCT FROM PHOTO · 0 MARKETPLACE SEARCHES/);
assert.match(app,/YES, THAT'S IT/);
assert.match(app,/ANOTHER PHOTO/);
assert.match(app,/READ BARCODE PHOTO/,'barcode photo must require an explicit read step');
assert.match(app,/Barcode photo captured/,'barcode photo capture must give visible confirmation');
assert.match(app,/sealedBarcodePreview/,'barcode photo preview must be rendered before reading');
assert.match(app,/Cloudflare Workers AI/i);
assert.match(app,/fetch\(`\$\{String\(cfg\.endpoint\).*\/sealed\/identify/s,'front end should send photo only to Scout sealed-identify endpoint');
const typeRouteStart=worker.indexOf('url.pathname === "/sealed/classify-type"');
const typeRouteEnd=worker.indexOf('url.pathname === "/sealed/identify"',typeRouteStart);
const typeRoute=worker.slice(typeRouteStart,typeRouteEnd);
assert.ok(typeRouteStart>=0&&typeRouteEnd>typeRouteStart,'type classifier route should be isolated before full vision route');
assert.doesNotMatch(typeRoute,/SERPAPI_KEY|runEbaySearch|serpapi\.com|APIFY_TOKEN|CARD_API_KEY/i,'type classifier must not call marketplace providers');
assert.match(typeRoute,/Do NOT re-identify the product/,'type classifier prompt must preserve barcode-confirmed identity');
assert.match(typeRoute,/marketplaceSearchesUsed:\s*0/,'type classifier must report zero marketplace searches');
const marketRouteStart=worker.indexOf('url.pathname === "/sealed/value-check"');
const marketRouteEnd=worker.indexOf('url.pathname === "/sealed/classify-type"',marketRouteStart);
const marketRoute=worker.slice(marketRouteStart,marketRouteEnd);
assert.ok(marketRouteStart>=0&&marketRouteEnd>marketRouteStart,'market route should be isolated before type classifier');
assert.match(marketRoute,/SERPAPI_KEY/,'market route should require SerpApi');
assert.match(marketRoute,/marketplaceSearchesUsed:\s*1/,'fresh market search must report one marketplace search');
assert.match(marketRoute,/cacheHit:\s*true[\s\S]*marketplaceSearchesUsed:\s*0/,'cached market result must cost zero marketplace searches');
assert.doesNotMatch(marketRoute,/APIFY_TOKEN|CARD_API_KEY/i,'sealed market route should not spend secondary-provider calls');
console.log('Sealed Product Scout vision tests passed.');
