const assert=require('node:assert/strict');
const fs=require('node:fs');
const worker=fs.readFileSync('src/index.js','utf8');
const app=fs.readFileSync('sealed-product-scout.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const wrangler=fs.readFileSync('wrangler.jsonc','utf8');

assert.match(worker,/const VERSION = "3\.48\.0"/);
assert.match(wrangler,/"ai"\s*:\s*\{\s*"binding"\s*:\s*"AI"/s,'Workers AI binding must be configured');
assert.match(worker,/\/sealed\/identify/,'sealed vision endpoint must exist');
assert.match(worker,/\/sealed\/barcode-identify/,'sealed barcode endpoint must exist');
assert.match(worker,/\/sealed\/classify-type/,'sealed product type classifier endpoint must exist');
assert.match(worker,/\/sealed\/value-check/,'sealed market value endpoint must exist');
assert.match(worker,/\/sealed\/rip-quality/,'sealed rip-quality endpoint must exist');
assert.match(app,/CHECK MARKET VALUE · 1 SEARCH MAX/,'sealed scanner must expose the one-search market check');
assert.match(app,/sealed\/value-check/,'front end must call the sealed market endpoint');
assert.match(app,/rawField=byId\(\"sealedShelfPrice\"\)/,'market check must read the currently entered shelf price');
assert.match(app,/saveDraft\(\{shelfPrice,store:/,'market check must auto-save the entered shelf price');
assert.match(worker,/engine\", \"ebay/,'sealed market check must use the eBay search engine');
assert.ok(worker.includes('rip\\s*(?:&|and)\\s*ship'),'sealed market check must reject rip-and-ship listings');
assert.match(worker,/sealed:value:v3:/,'sealed market benchmark changes must invalidate stale cached results');
assert.match(worker,/sealedMarketIdentityMatches/,'sealed market check must require product-family identity matches');
assert.match(worker,/sealedMarketIsMultiUnit/,'sealed market check must reject multi-box lots');
assert.match(worker,/sealedMarketCompetitiveSummary/,'sealed market check must use a competitive-price band');
assert.match(worker,/Math\.min\(10, all\.length\)/,'competitive-price band must use at most ten lowest clean matches');
assert.match(app,/Competitive-listing median/,'sealed market UI must label the competitive median clearly');
assert.match(app,/totalCleanCount/,'sealed market UI must show competitive matches versus total clean listings');
assert.match(app,/GET SCOUT'S BUY CALL · 2 RESEARCH SEARCHES MAX/,'sealed scanner must expose the final buy recommendation');
assert.match(app,/sealed\/rip-quality/,'front end must call rip-quality endpoint');
assert.match(app,/SCOUT'S FINAL VERDICT/,'rip-quality result must show a final verdict');
assert.match(app,/TOP CHASES/,'rip-quality result must explain chase cards');
assert.match(app,/PULL ODDS/,'rip-quality result must show pull odds or explain their absence');
assert.match(app,/WHAT COLLECTORS ARE SAYING/,'rip-quality result must summarize collector feedback');
assert.match(app,/TAKE FRONT PHOTO FOR PRODUCT TYPE/,'barcode-confirmed products should request a front photo when type is missing');
assert.match(app,/sealed\/classify-type/,'front end must call the narrow product type classifier');
assert.match(app,/classifyProductTypeFromPhoto/,'front end should classify only package type after barcode identity');
assert.match(worker,/api\.upcitemdb\.com\/prod\/trial\/lookup/,'barcode lookup should use the free UPC database endpoint');
assert.match(app,/SCAN BARCODE/,'sealed scanner must expose barcode photo capture');
assert.match(app,/BarcodeDetector/,'browser-native barcode detection should be attempted when supported');
assert.match(app,/sealed\/barcode-identify/,'barcode UI must call the Scout barcode endpoint');
assert.match(worker,/@cf\/moondream\/moondream3\.1-9B-A2B/,'Cloudflare-hosted vision model must be used');
assert.match(worker,/raw\?\.answer/,'Moondream query answer envelope must be parsed');
assert.match(worker,/stream:\s*false/,'Moondream query must use non-streaming output for deterministic parsing');
assert.match(worker,/marketplaceSearchesUsed:\s*0/,'vision endpoint must explicitly report zero marketplace searches');
const start=worker.indexOf('url.pathname === "/sealed/identify"');
const end=worker.indexOf('url.pathname === "/automation/status"',start);
const route=worker.slice(start,end);
assert.ok(start>=0&&end>start,'sealed route should be isolated before automation route');
assert.doesNotMatch(route,/SERPAPI_KEY|runEbaySearch|serpapi\.com|APIFY_TOKEN|CARD_API_KEY/i,'vision route must not call marketplace providers');
assert.match(app,/IDENTIFY PRODUCT FROM PHOTO · 0 MARKETPLACE SEARCHES/);
assert.match(app,/YES, THAT'S IT/);
assert.match(app,/ANOTHER PHOTO/);
assert.match(app,/READ BARCODE PHOTO/,'barcode photo must require an explicit read step');
assert.match(app,/Barcode photo captured/,'barcode photo capture must give visible confirmation');
assert.match(app,/sealedBarcodePreview/,'barcode photo preview must be rendered before reading');
assert.match(app,/Cloudflare Workers AI/i);
assert.match(app,/fetch\(`\$\{String\(cfg\.endpoint\).*\/sealed\/identify/s,'front end should send photo only to Scout sealed-identify endpoint');
const ripRouteStart=worker.indexOf('url.pathname === "/sealed/rip-quality"');
const ripRouteEnd=worker.indexOf('url.pathname === "/sealed/classify-type"',ripRouteStart);
const ripRoute=worker.slice(ripRouteStart,ripRouteEnd);
assert.ok(ripRouteStart>=0&&ripRouteEnd>ripRouteStart,'rip-quality route should be isolated before type classifier');
assert.match(ripRoute,/SERPAPI_KEY/,'rip-quality route should require research search access');
assert.ok(worker.includes('url.searchParams.set("engine", "google")'),'rip-quality research must use Google searches');
assert.match(ripRoute,/researchSearchesUsed:\s*2|researchSearchesUsed\s*=\s*2/,'fresh rip research must use at most two planned research searches');
assert.match(ripRoute,/marketplaceSearchesUsed:\s*0/,'rip-quality research must use zero marketplace searches');
assert.doesNotMatch(ripRoute,/engine", "ebay|APIFY_TOKEN|CARD_API_KEY/i,'rip-quality route must not spend marketplace-provider calls');
assert.ok(worker.includes('@cf/meta/llama-3.3-70b-instruct-fp8-fast'),'rip-quality synthesis must use the Cloudflare text model');
assert.ok(worker.includes('NEVER invent, estimate, calculate, or extrapolate an exact pull odd'),'rip-quality prompt must prohibit invented pull odds');
assert.match(worker,/sealed:intel:v19:/,'sealed product intelligence must use a reusable mode-scoped product cache');
assert.match(worker,/sealedRipWeightedScore/,'final verdict must combine price, chases, pull evidence, and sentiment');
assert.match(worker,/sealedRipProductEvidenceCount/,'buy recommendation must count the three product-quality evidence pillars');
assert.match(worker,/sealedRipProductEvidenceCount\(parts\) < 2/,'buy recommendation must require two of three product-quality pillars');
assert.match(worker,/sealedRipWeightProfile/,'sealed research must route scoring weights by category');
assert.ok(worker.includes('price: 30, chase: 35, pull: 20, sentiment: 15'),'Pokémon must emphasize chase quality plus observed pull experience');
assert.ok(worker.includes('price: 30, chase: 45, pull: 10, sentiment: 15'),'Magic must emphasize set/playable value more heavily');
assert.ok(worker.includes('price: 35, chase: 35, pull: 10, sentiment: 20'),'sports must retain the sports-card weighting profile');
assert.match(worker,/sealedRipIntelligenceCacheKey/,'product intelligence must be cached independently of shelf price');
assert.ok(worker.includes('researchMode === \"showdown\" ? 3 : 14'),'Showdown price-guide intelligence should refresh after three days while single-product intelligence remains reusable for fourteen');
assert.match(worker,/intelligenceTtlDays \* 24 \* 60 \* 60/,'mode-specific intelligence TTL must be applied to cache writes');
assert.match(worker,/sealedRipChaseContextSupported/,'verified checklist structure must support chase-quality scoring without invented chase names');
assert.match(app,/STEP 4 · SHOULD I BUY THIS\?/,'sealed scanner must frame the final step as the purchase decision');
assert.match(app,/Confidence: <strong>/,'sealed scanner must show recommendation confidence');
assert.match(app,/Exact-format pull odds were not reliably verified/,'missing exact odds must be shown as optional instead of blocking a recommendation');
assert.match(index,/sealed-product-scout\.js\?v=6\.5\.3/,'sealed scanner cache-bust must advance for Showdown reliability fixes');
assert.match(worker,/sealedRipExpandEvidenceRows/,'rip research must expand high-quality source pages beyond search snippets');
assert.match(worker,/sealedRipReaderPageText/,'trusted authority pages must have a rendered-reader fallback when direct HTML is thin or blocked');
assert.match(worker,/sealedRipSerpEvidenceText/,'rip research must retain structured Google evidence when publisher page reading is blocked');
assert.match(worker,/ampLink/,'authority research must retain Google AMP links when available');
assert.match(worker,/cachedPageLink/,'authority research must retain Google cached-page links when available');
assert.match(worker,/device = \"\"/,'Google research helper must support a mobile authority request');
assert.match(worker,/sealedRipGoogleSearch\(checklistQuery, env\.SERPAPI_KEY, 18000, \"mobile\"\)/,'authority lookup must request mobile results so AMP links can be exposed');
assert.match(worker,/https:\/\/r\.jina\.ai\//,'authority reader fallback must use the documented Jina Reader URL prefix');
assert.match(worker,/sealedRipCanUseReader/,'reader fallback must be restricted to trusted authority domains');
assert.match(worker,/sealedRipPageHasUsefulSignals/,'authority page expansion must verify useful chase or odds signals before accepting direct HTML');
assert.match(worker,/sealedRipEvidencePriority/,'rip research must prioritize official and checklist sources for page expansion');
assert.match(worker,/sealedRipPrimaryAuthoritySite/,'rip research must use one reliable primary authority domain per category');
assert.match(worker,/site:beckett\.com/,'sports rip research must force the authoritative search onto Beckett');
assert.match(worker,/const authorityYear = String\(identity\?\.year/,'authority discovery must normalize season punctuation');
assert.match(worker,/sealedRipResearchTerms/,'research query vocabulary must route by category');
assert.ok(worker.includes('special illustration rare'),'Pokémon research must know SIR terminology');
assert.ok(worker.includes('illustration rare'),'Pokémon research must know IR terminology');
assert.ok(worker.includes('hyper rare'),'Pokémon research must know Hyper Rare terminology');
assert.ok(worker.includes('community pull-rate or hit-rate samples'),'Pokémon guidance must allow clearly labeled community pull-rate evidence');
assert.ok(worker.includes('borderless/showcase treatments'),'Magic guidance must know borderless/showcase treatments');
assert.ok(worker.includes('Special Guests/bonus sheets'),'Magic guidance must know Special Guests and bonus sheets');
assert.ok(worker.includes('PLAYABLE/VALUE QUALITY'),'Magic chase scoring must include playable/set value');
assert.match(worker,/function sealedRipAuthorityQuery/,'authority discovery must route by category');
assert.ok(worker.includes('product \"card image gallery\" collecting booster contents'),'Magic authority search must discover Wizards set-level pages before exact-format extraction');
assert.match(worker,/function sealedRipPromptSignals\(rows, category = ""\)/,'compact evidence extraction must be category aware');
assert.ok(worker.includes('cosmic foil'),'Magic signal extraction must understand Magic-specific treatments');
assert.ok(worker.includes('special illustration rare'),'category-aware extraction must retain Pokémon chase vocabulary');
assert.match(worker,/function sealedRipVerifiedChaseScore/,'verified Magic structure must protect against contradictory zero set-value scores');
assert.match(worker,/function sealedRipFormatAccessContextSupported/,'Shelf Showdown must locally verify exact-format chase access');
assert.match(worker,/function sealedRipShowdownAnalysisComplete/,'Showdown cache must reject incomplete intelligence');
assert.match(worker,/function sealedRipFailureLanes/,'failed Showdown research must expose typed lane diagnostics');
assert.ok(worker.includes('const activeSynthesisSchema = researchMode === "showdown" ? showdownSchema : schema'),'Showdown must use a smaller authority-only synthesis schema');
assert.ok(worker.includes('sealed rip primary synthesis/parse failed'),'malformed AI JSON must trigger the compact retry too');
assert.match(worker,/function sealedRipFormatMentions/,'exact-format validation must retain location-aware format mentions');
assert.match(worker,/function sealedRipFormatAccessSectionSupported/,'exact-format validation must bind chase signals to the same local product section');
assert.match(worker,/function sealedRipFormatAccessLocalEvidence/,'exact-format scoring must use only section-local authority evidence');
assert.ok(worker.includes('const nearestDistance = Math.min') && worker.includes('nearest.some(row => compatible.has(row.hit.key))'),'format access must reject a chase signal whose nearest format label belongs to another product configuration');
assert.match(worker,/function sealedRipPriceGuideQuery/,'Shelf Showdown must use one aggregate singles price-guide search');
assert.ok(worker.includes('site:tcgplayer.com'),'Magic Chase Depth should use TCGplayer set pricing');
assert.ok(worker.includes('site:tcgplayer.com'),'Pokemon Chase Depth should use TCGplayer set pricing');
assert.ok(worker.includes('site:sportscardspro.com'),'sports Chase Depth should use SportsCardsPro set pricing');
assert.match(worker,/function sealedRipChaseValueSupported/,'candidate card prices must be locally validated against price-guide evidence');
assert.match(worker,/function sealedRipPriceGuideExcerpt/,'price-guide page reading must preserve local price records');
assert.match(worker,/function sealedRipPriceGuideAtomicBlocks/,'Chase Depth verification must operate on bounded local records');
assert.match(worker,/function sealedRipChaseValueProof/,'accepted singles values must carry a local evidence proof');
assert.match(worker,/function sealedRipPriceGuidePriceBasis/,'price validation must distinguish Market Price from Ungraded evidence');
assert.match(worker,/sportscardspro\.com.*ungraded/s,'SportsCardsPro values must require ungraded context');
assert.match(worker,/tcgplayer\.com.*market\\s\+price/s,'TCGplayer values must require Market Price context');
assert.match(worker,/psa\|bgs\|sgc\|cgc/i,'atomic price validation must recognize graded-price contamination');
const atomicStart=worker.indexOf('function sealedRipChaseValueProof');
const atomicEnd=worker.indexOf('function sealedRipNormalizeChaseValues',atomicStart);
const atomicBlock=worker.slice(atomicStart,atomicEnd);
assert.ok(atomicStart>=0&&atomicEnd>atomicStart,'atomic Chase Depth validator block must exist');
assert.doesNotMatch(atomicBlock,/at - 500|at \+ 850/,'Chase Depth must not use the old broad nearby-price window');

assert.match(worker,/function sealedRipChaseDepthMetrics/,'verified singles values must produce a deterministic Chase Depth score');
assert.ok(worker.includes('sportscardspro\\.com'),'SportsCardsPro must be allowed as a readable price-guide source');
assert.match(worker,/function sealedRipAuthorityRows/,'authority evidence must have an explicit typed lane');
assert.match(worker,/function sealedRipPullEvidenceRows/,'pull evidence must explicitly exclude the singles-price lane');
assert.match(worker,/function sealedRipLaneState/,'normalized analysis must expose lane completeness');
assert.ok(worker.includes('row?.queryKind === "checklist-and-odds"'),'authority lane must be checklist/authority only');
assert.ok(worker.includes('row?.queryKind === "checklist-and-odds" || row?.queryKind === "collector-reports"'),'pull evidence may use authority/community but never price-guide rows');
assert.doesNotMatch(worker,/function sealedRipChaseDepthSetFloor/,'price-guide Chase Depth must not impose a Set Strength floor');
assert.ok(worker.includes('const mainEvidenceRows = researchMode === "showdown"'),'Showdown must isolate price-guide rows from the main synthesis prompt');
assert.ok(worker.includes('row.queryKind !== "singles-price-guide"'),'main Showdown evidence must exclude singles price-guide rows');
assert.ok(worker.includes('const authorityCandidates = candidates'),'page expansion must reserve capacity for authoritative product evidence');
assert.ok(worker.includes('const priceGuideCandidates = candidates'),'price-guide page expansion must have a separate bounded lane');
assert.ok(worker.includes('.slice(0, 2);'),'price-guide page expansion must stay tightly bounded');
assert.ok(worker.includes('sealed rip primary synthesis/parse failed; trying compact authority-only retry'),'rip analysis must retry once on synthesis or parse failure without another search');
assert.ok(worker.includes('synthesisRetryUsed'),'rip response must expose whether the compact synthesis fallback was needed');
assert.ok(worker.includes('AUTHORITY-ONLY RECOVERY'),'recovery for set/chase and odds must be authority-only');
assert.ok(worker.includes('PRICE-GUIDE-ONLY RECOVERY'),'Chase Depth recovery must be price-guide-only');
assert.ok(worker.includes('const authorityRows = sealedRipAuthorityRows'),'normalization must split authority evidence before validation');
assert.ok(worker.includes('const priceGuideRows = sealedRipPriceGuideRows'),'normalization must split price-guide evidence before validation');
assert.ok(worker.includes('lanes,'),'normalized response must expose lane status');
assert.ok(app.includes('Evidence lanes:'),'Showdown UI must display evidence-lane status');
assert.ok(app.includes('lanes:row.analysis?.lanes||{}'),'Showdown persistence must preserve lane status');
assert.ok(worker.includes('const chaseEvidenceAvailable = chaseCards.length > 0 || chaseContextAvailable'),'Set/chase evidence must come only from the authority lane');
assert.match(worker,/function sealedRipFormatAccessFallbackScore/,'exact-format context must have a deterministic fallback score');
assert.ok(worker.includes('const formatAccessScore = formatAccessEvidenceAvailable\n    ? sealedRipFormatAccessFallbackScore(authorityRows, identity)'),'exact-format score must be deterministic from locally verified authority evidence rather than the AI score');
assert.ok(worker.includes('sealedRipFormatAccessSectionSupported(rawFormatSummary, identity)'),'format-access summary must itself name the exact format next to a chase/treatment signal');
assert.ok(worker.includes('const formatAccessEvidenceAvailable = formatAccessContextAvailable'),'locally verified exact-format evidence must not depend on an AI boolean flag');
assert.ok(worker.includes('researchMode === "showdown"'),'Showdown must swap community research for aggregate price-guide research');
assert.ok(app.includes('researchMode:"showdown"'),'front end must request Showdown research mode');
assert.ok(app.includes('CHASE DEPTH'),'Showdown must display Chase Depth');
assert.match(worker,/function sealedRipChaseCanonicalIdentity/,'Chase Depth must canonicalize parallel treatments into core card identities');
assert.match(worker,/function sealedRipChaseIdentityGroups/,'Chase Depth must group verified price-guide rows by canonical card identity');
assert.ok(worker.includes('const uniqueRows = groups.map(group => group.representative)'),'Chase Depth thresholds must use one representative price per canonical identity');
assert.ok(worker.includes('const parallelBreadth = Math.max(0, variantCount - uniqueCount)'),'parallel breadth must be measured separately from unique chase depth');
assert.ok(worker.includes('chaseDepthUniqueCount'),'normalized response must expose unique chase identity count');
assert.ok(worker.includes('top 10 unique values total'),'Chase Depth summary must describe canonicalized value totals');
assert.ok(app.includes('let weighted=depth*.35+format*.25+price*.20+set*.15'),'Showdown weights must prioritize Chase Depth without inventing missing support');
assert.ok(app.includes('const rankable=missing.length===0'),'Showdown must explicitly mark incomplete products unrankable');
assert.ok(app.includes('INCOMPLETE · NOT RANKED'),'Showdown must visibly label incomplete products');
assert.ok(app.includes('rankable&&place===1&&rankableCount>=2'),'Best Shelf Buy must require at least two rankable products');
assert.ok(app.includes('status:row.metrics?.rankable?"ranked":"incomplete"'),'stored Showdown results must preserve ranked vs incomplete status');
assert.ok(app.includes('showdownScore(item,market,analysis,error)'),'research failures must flow into rankability instead of receiving fallback scores');
assert.doesNotMatch(app,/const depth=analysis\?\.chaseDepthEvidenceAvailable\?showdownMetric\(analysis\?\.chaseDepthScore,30\):30/,'missing Chase Depth must not receive a synthetic score');
assert.doesNotMatch(app,/const format=analysis\?\.formatAccessEvidenceAvailable\?showdownMetric\(analysis\?\.formatAccessScore,35\):35/,'missing Format Access must not receive a synthetic score');
assert.ok(worker.includes('Collector Booster')&&worker.includes('Play Booster')&&worker.includes('Jumpstart Booster'),'specialized Magic boosters must remain first-class product types');
assert.ok(worker.includes('formatAccessEvidenceAvailable'),'rip analysis must expose exact-format access evidence');
assert.ok(worker.includes('formatAccessScore'),'rip analysis must expose an exact-format access score');
assert.ok(worker.includes('collector_booster'),'Magic Collector Booster must be a distinct sealed format');
assert.ok(worker.includes('play_booster'),'Magic Play Booster must be a distinct sealed format');
assert.ok(worker.includes('jumpstart_booster'),'Magic Jumpstart Booster must be a distinct sealed format');
assert.match(worker,/researchTerms\.authority/,'authority query must use category-specific research terms');
assert.match(worker,/researchTerms\.community/,'community query must use category-specific research terms');
assert.match(worker,/url\.searchParams\.set\(\"num\", \"20\"\)/,'rip research should inspect a broader Google result page without adding a third search');
assert.match(worker,/out\.length >= 12/,'rip research should retain enough candidates to reach lower-ranked odds sources');
assert.match(worker,/const chaseEvidenceAvailable = chaseCards\.length > 0 \|\| chaseContextAvailable/,'chase quality may use verified checklist structure even when named chases are unavailable');
assert.match(worker,/sealedRipPromptSignals/,'rip research must build a compact chase-and-odds signal digest');
assert.match(worker,/authorityRecoveryPrompt/,'authority recovery must retry chase/odds extraction without another search');
assert.match(worker,/priceGuideRecoveryPrompt/,'price-guide recovery must retry Chase Depth extraction without another search');
assert.match(worker,/const researchMix = \{/,'rip response must expose safe source-mix diagnostics for troubleshooting');
assert.match(worker,/missingChases.*missingOdds/s,'compact recovery must only run when chase or odds extraction is missing');
assert.match(worker,/rich_snippet/,'rip research should retain rich Google result text when available');
assert.match(worker,/sealedRipResearchSet/,'rip research must normalize barcode-style product titles into a searchable set name');
assert.match(worker,/requiredMatches = Math\.min\(2, tokens\.length\)/,'rip source filter must not require every incidental barcode-title token');
assert.match(worker,/if \(!evidenceRows\.length\)/,'one trustworthy source should be allowed to produce a guarded partial result');
assert.match(worker,/chaseEvidenceAvailable/,'rip research must explicitly track whether named chase evidence exists');
assert.match(worker,/NEED MORE DATA/,'rip verdict must refuse BUY recommendations when key product-quality evidence is missing');
assert.match(worker,/site:reddit\.com\/r\/basketballcards/,'basketball sentiment search must target the basketball-card community');
assert.match(app,/Product evidence: <strong>/,'rip UI must show product-evidence completeness');
assert.match(app,/v===null\|\|v===undefined/,'rip UI must render missing component scores as N/A, not zero');

assert.match(worker,/sealedRipEvidenceYearConflict/,'sealed research must reject explicitly wrong-season authority results');
assert.match(worker,/sealedRipEvidenceBrandConflict/,'sealed research must reject conflicting manufacturer results');
assert.ok(worker.includes('["Baseball", "Basketball", "Football"].includes(category) && /\\bvalue\\s+box\\b/i.test(text)'),'sports UPC titles using Value Box must auto-fill Product Type');
assert.match(worker,/positives: sentimentEvidenceAvailable \?/,'collector positives must be hidden when collector evidence is unavailable');
assert.match(worker,/negatives: sentimentEvidenceAvailable \?/,'collector negatives must be hidden when collector evidence is unavailable');

assert.match(worker,/sealedRipCategoryGuidance/,'sealed analysis prompt must inject a category-specific playbook');
assert.match(worker,/sealedRipScoreLabels/,'sealed response must expose category-specific score labels');
assert.match(worker,/sealedRipChaseContextSupported\(evidenceRows, category = ""\)/,'chase evidence detection must understand category vocabulary');
assert.match(app,/researchProfile/,'sealed UI must show which research profile made the recommendation');
assert.match(app,/scoreLabels\?\.chase/,'sealed UI must render category-specific score labels');

const typeRouteStart=worker.indexOf('url.pathname === "/sealed/classify-type"');
const typeRouteEnd=worker.indexOf('url.pathname === "/sealed/identify"',typeRouteStart);
const typeRoute=worker.slice(typeRouteStart,typeRouteEnd);
assert.ok(typeRouteStart>=0&&typeRouteEnd>typeRouteStart,'type classifier route should be isolated before full vision route');
assert.doesNotMatch(typeRoute,/SERPAPI_KEY|runEbaySearch|serpapi\.com|APIFY_TOKEN|CARD_API_KEY/i,'type classifier must not call marketplace providers');
assert.match(typeRoute,/Do NOT re-identify the product/,'type classifier prompt must preserve barcode-confirmed identity');
assert.match(typeRoute,/marketplaceSearchesUsed:\s*0/,'type classifier must report zero marketplace searches');
const marketRouteStart=worker.indexOf('url.pathname === "/sealed/value-check"');
const marketRouteEnd=worker.indexOf('url.pathname === "/sealed/rip-quality"',marketRouteStart);
const marketRoute=worker.slice(marketRouteStart,marketRouteEnd);
assert.ok(marketRouteStart>=0&&marketRouteEnd>marketRouteStart,'market route should be isolated before type classifier');
assert.match(marketRoute,/SERPAPI_KEY/,'market route should require SerpApi');
assert.match(marketRoute,/marketplaceSearchesUsed:\s*1/,'fresh market search must report one marketplace search');
assert.match(marketRoute,/cacheHit:\s*true[\s\S]*marketplaceSearchesUsed:\s*0/,'cached market result must cost zero marketplace searches');
assert.doesNotMatch(marketRoute,/APIFY_TOKEN|CARD_API_KEY/i,'sealed market route should not spend secondary-provider calls');

assert.match(worker,/function sealedRipVerifiedPullScore/,'verified pull odds must protect against contradictory zero pull scores');
assert.match(worker,/communitySourceCount >= 2/,'collector sentiment must require recurring community evidence');
assert.ok(worker.includes('Never say "many collectors"'),'collector synthesis must avoid broad consensus claims from thin evidence');
assert.match(worker,/function sealedRipOddsRowSupported/,'pull odds must be validated as item+odds pairs inside matching-set evidence');
assert.match(worker,/sealedRipEvidenceRowMatchesIdentity/,'pull-odds evidence must match the scanned set identity');
assert.match(worker,/COMMUNITY EVIDENCE — use ONLY this section/,'collector sentiment must be isolated from checklist evidence');
assert.match(worker,/sealedRipTemperCollectorSummary/,'collector copy must suppress unsupported promotional conclusions');
assert.match(worker,/function sealedRipFormatTextCompatible/,'pull odds must enforce exact sealed-format compatibility');
assert.match(worker,/function sealedRipVariantTextCompatible/,'retailer-exclusive pull odds must match the scanned variant');
assert.ok(worker.includes('keys.add("value_box")'),'sports Value Box wording must remain compatible with standard Blaster classification');
assert.ok(worker.includes('Every pullOdds.note MUST name the applicable sealed format'),'AI extraction must label the format attached to every supported odd');
assert.match(worker,/function sealedRipCommunityRowCompatible/,'community source titles naming another format must be rejected');
assert.match(worker,/function sealedRipCommunitySentenceCompatible/,'format-specific community sentences must match the scanned format');
assert.match(worker,/sealedRipCommunityEvidenceText\(evidenceRows, identity\)/,'collector prompt must receive format-scoped community evidence');
assert.ok(worker.includes("Never import Hobby, Mega, Hanger, Fanatics"),'collector synthesis must forbid cross-format opening economics');
assert.match(worker,/function sealedRipFilterCollectorText/,'final collector summary must be post-filtered by exact format');
assert.match(worker,/function sealedRipFilterCollectorItems/,'collector bullets must be post-filtered by exact format');
assert.match(worker,/function sealedRipCollectorFormatConflict/,'cross-format synthesized sentiment must invalidate the sentiment score');
assert.ok(worker.includes('Scout discarded collector sentiment because the synthesized comments mixed a different sealed format'),'cross-format sentiment must fail closed instead of scoring questionable copy');

console.log('Sealed Product Scout vision tests passed.');

const showdownFront=fs.readFileSync('sealed-product-scout.js','utf8');

assert.ok(showdownFront.includes('scoutSealedShelfShowdownV1'),'front end must persist a Shelf Showdown queue');
assert.ok(showdownFront.includes('ADD TO SHELF SHOWDOWN'),'front end must offer zero-search add-to-showdown flow');
assert.ok(showdownFront.includes('RANK MY SHELF'),'front end must expose Shelf Showdown ranking');
assert.ok(showdownFront.includes('function runShelfShowdown'),'front end must orchestrate multi-product research');
assert.ok(showdownFront.includes('FORMAT ACCESS'),'ranking must show exact-format access separately');
assert.ok(showdownFront.includes('SHOWDOWN_MAX=5'),'Shelf Showdown must cap the first version at five products');
