const fs = require('fs');
const assert = require('assert');
const worker = fs.readFileSync('src/index.js','utf8');
assert.ok(worker.includes('const VERSION = "3.49.0";'), 'Worker must be v3.49.0');
assert.ok(worker.includes('sealed:intel:v20:'), 'Showdown intelligence cache must advance to v19');
assert.ok(worker.includes('? { type: "json_object" }'), 'Showdown primary synthesis must use JSON object mode instead of strict schema mode');
assert.ok(worker.includes('If Showdown JSON mode itself fails'), 'Showdown retry must intentionally avoid repeating the same structured-mode failure');
assert.ok(worker.includes('retryOptions.response_format = { type: "json_schema", json_schema: activeSynthesisSchema };'), 'single-product retry must retain its existing strict schema behavior');
assert.ok(worker.includes('response_format: { type: "json_object" }'), 'Showdown price-guide recovery must use JSON object mode');
assert.ok(worker.includes('synthesisMode: researchMode === "showdown" ? "json_object_with_plain_retry" : "json_schema"'), 'response diagnostics must expose the Showdown synthesis mode');
assert.ok(worker.includes('sealedRipAiJson(primaryRaw)'), 'primary JSON output must still be parsed locally');
assert.ok(worker.includes('sealedRipAiJson(retryRaw)'), 'retry JSON output must still be parsed locally');
console.log('Showdown JSON reliability tests passed.');
