const fs=require('fs');
const assert=require('assert');
const worker=fs.readFileSync('src/index.js','utf8');
const app=fs.readFileSync('sealed-product-scout.js','utf8');
const index=fs.readFileSync('index.html','utf8');
assert.ok(worker.includes('const VERSION = "3.50.0";'));
assert.ok(worker.includes('url.pathname === "/sealed/ai-health"'), 'Worker must expose a Showdown AI health endpoint');
assert.ok(worker.includes('prompt: "Reply exactly OK."') && worker.includes('max_tokens: 4'), 'health probe must be tiny');
const healthStart=worker.indexOf('url.pathname === "/sealed/ai-health"');
const healthEnd=worker.indexOf('url.pathname === "/sealed/rip-quality"',healthStart);
const health=worker.slice(healthStart,healthEnd);
assert.ok(healthStart>=0&&healthEnd>healthStart,'AI health route must precede rip-quality');
assert.ok(health.includes('marketplaceSearchesUsed: 0')&&health.includes('researchSearchesUsed: 0'),'health check must spend zero searches');
assert.ok(health.includes('sealedRipAiFailureInfo(err)'),'health failures must use safe typed diagnostics');
assert.ok(app.includes('/sealed/ai-health'),'Showdown must check AI health before product research');
const appHealth=app.indexOf('/sealed/ai-health');
const appValue=app.indexOf('/sealed/value-check',appHealth);
assert.ok(appHealth>=0&&appValue>appHealth,'AI health check must occur before the first market/product research call');
assert.ok(app.includes('No marketplace or product-research searches were used.'),'health failure must clearly promise zero search spend');
assert.ok(index.includes('sealed-product-scout.js?v=6.5.4'),'frontend cache-bust must advance');
console.log('Showdown AI health tests passed.');
