const assert=require("node:assert/strict");
const fs=require("node:fs");
const html=fs.readFileSync("index.html","utf8");
assert.match(html,/targetYear:p\.targetYear/);
assert.match(html,/targetAutoPreference/);
assert.match(html,/targetMaxPrice/);
assert.match(html,/function targetPrimaryStatus\(p\)/);
assert.match(html,/if\(p\?\.incoming\)return \{key:"incoming"/);
assert.match(html,/function applyStructuredTarget\(p,data=\{\}\)/);
assert.match(html,/function clearStructuredTarget\(p\)/);
const clearBlock=html.match(/function clearStructuredTarget\(p\)\{[\s\S]*?(?=\nfunction purchaseSummary)/)?.[0]||"";
assert.ok(clearBlock,"clear helper should be present");
assert.doesNotMatch(clearBlock,/\n\s*clearStructuredTarget\(p\);/,"clear helper must not call itself");
assert.match(clearBlock,/p\.target="";p\.targetNotes="";/);
assert.match(html,/function removeCurrentTarget\(\)[\s\S]*?clearStructuredTarget\(p\);/);
assert.match(html,/id="targetSummary"/);
assert.match(html,/id="editTargetBtn"/);
assert.match(html,/openTargetManage\(currentPlayer\)/);
assert.match(html,/source:"Scout Target Finder"/);
assert.match(html,/source:"Card Shop Mode"/);
assert.match(html,/huntNeedPlayers\(\)\{return PLAYERS\.filter\(p=>!p\.owned&&!p\.incoming&&!p\.target\)\}/);
const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];
assert.ok(scripts.length,"main script should exist");
for(const m of scripts)new Function(m[1]);
const lab=fs.readFileSync("phase6-find-target.html","utf8");
assert.match(lab,/targetYear:Number\(suggestion\.year\)/);
assert.match(lab,/targetMaxPrice/);
console.log("Structured target management contract passed.");
