const assert=require("node:assert/strict");
const fs=require("node:fs");
const vm=require("node:vm");
const html=fs.readFileSync("index.html","utf8");
function block(start,end){
  const a=html.indexOf(start),b=html.indexOf(end,a);
  assert.ok(a>=0&&b>a,`missing block ${start}`);
  return html.slice(a,b);
}
const parser=block("function phase3bParseTarget(label)","function phase3bScoutTarget(p)");
const helpers=block("function targetIdentity(p)","function purchaseSummary(p)");
const ctx={};vm.createContext(ctx);vm.runInContext(parser+"\n"+helpers+"\nthis.api={targetIdentity,targetIdentityLabel,targetPreferenceBits,targetSearchHint,targetPrimaryStatus,applyStructuredTarget,clearStructuredTarget};",ctx);
const api=ctx.api;
const legacy={target:"1980 Topps #482",targetNotes:"favorite rookie"};
assert.deepEqual(JSON.parse(JSON.stringify(api.targetIdentity(legacy))),{year:1980,set:"Topps",cardNum:"482"});
const p={target:""};
api.applyStructuredTarget(p,{year:1980,set:"Topps",cardNum:"482",grader:"PSA",grade:"7",autoPreference:"Autograph required",maxPrice:75,notes:"clean copy",listingUrl:"https://example.test",source:"Scout Target Finder"});
assert.equal(p.target,"1980 Topps #482");
assert.equal(p.targetMaxPrice,75);
assert.match(api.targetSearchHint(p),/1980 Topps #482 PSA 7 autograph/i);
assert.deepEqual(JSON.parse(JSON.stringify(api.targetPrimaryStatus({owned:false,incoming:false,target:p.target}))),{key:"target",label:"🎯 TARGET"});
assert.equal(api.targetPrimaryStatus({owned:true,incoming:false,target:p.target}).key,"owned");
assert.equal(api.targetPrimaryStatus({owned:true,incoming:true,target:p.target}).key,"incoming");
api.clearStructuredTarget(p);assert.equal(p.target,"");assert.equal(p.targetMaxPrice,null);
assert.match(html,/targetSpec:p\.target\?/);
assert.match(html,/const structuredMax=Number\(currentPlayer\.targetMaxPrice\)/);
assert.match(html,/id="editTargetBtn"/);
assert.match(html,/id="removeTargetBtn"/);
assert.match(html,/id="targetAutoPreference"/);
console.log("Structured target tests passed.");
