window.DEEP_DRAFT_PLAYERS = [
  {rank:101,marketRank:101,player:"Los Angeles Rams D/ST",team:"LAR",pos:"DEF",tag:"DST TARGET",tier:"DST Tier 1",specialRank:3,note:"Elite D/ST option; still wait until the final rounds."},
  {rank:102,marketRank:102,player:"Jayden Reed",team:"GB",pos:"WR",tag:"SLEEPER",tier:"Tier 8",note:"Late WR upside."},
  {rank:103,marketRank:103,player:"Jaxson Dart",team:"NYG",pos:"QB",tag:"UPSIDE QB",tier:"Tier 8",note:"Late ceiling swing."},
  {rank:104,marketRank:104,player:"Michael Pittman",team:"PIT",pos:"WR",tag:"DEPTH",tier:"Tier 8",note:"Late-round WR depth."},
  {rank:105,marketRank:105,player:"Quentin Johnston",team:"LAC",pos:"WR",tag:"UPSIDE",tier:"Tier 8",note:"Late-round WR ceiling."},
  {rank:106,marketRank:106,player:"Matthew Stafford",team:"LAR",pos:"QB",tag:"LATE QB",tier:"Tier 8",note:"Veteran late-QB option."},
  {rank:107,marketRank:107,player:"Kenny Gainwell",team:"TB",pos:"RB",tag:"DEPTH",tier:"Tier 8",note:"Bench RB depth."},
  {rank:108,marketRank:108,player:"Josh Downs",team:"IND",pos:"WR",tag:"VALUE",tier:"Tier 8",note:"Late-round reception volume."},
  {rank:109,marketRank:109,player:"Jake Ferguson",team:"DAL",pos:"TE",tag:"LATE TE",tier:"Tier 8",note:"Wait-on-TE depth option."},
  {rank:110,marketRank:110,player:"Houston Texans D/ST",team:"HOU",pos:"DEF",tag:"DST TARGET",tier:"DST Tier 1",specialRank:1,note:"Scout's top D/ST; do not pay an early-round premium."},
  {rank:111,marketRank:111,player:"Patrick Mahomes",team:"KC",pos:"QB",tag:"FADE AT COST",tier:"Tier 8",note:"Recovery adds risk; Scout prefers healthier late-QB values."},
  {rank:112,marketRank:112,player:"Isaiah Likely",team:"NYG",pos:"TE",tag:"UPSIDE",tier:"Tier 8",note:"Late TE upside."},
  {rank:113,marketRank:113,player:"Aaron Jones Sr.",team:"MIN",pos:"RB",tag:"CAUTION",tier:"Tier 8",note:"Veteran bench depth."},
  {rank:114,marketRank:114,player:"KC Concepcion",team:"CLE",pos:"WR",tag:"UPSIDE",tier:"Tier 8",note:"Late rookie upside."},
  {rank:115,marketRank:115,player:"Stefon Diggs",team:"WAS",pos:"WR",tag:"DEPTH",tier:"Tier 8",note:"Veteran WR depth."},
  {rank:116,marketRank:116,player:"Seattle Seahawks D/ST",team:"SEA",pos:"DEF",tag:"DST TARGET",tier:"DST Tier 1",specialRank:4,note:"Top-tier D/ST target in the final rounds."},
  {rank:117,marketRank:117,player:"Wan'Dale Robinson",team:"TEN",pos:"WR",tag:"DEPTH",tier:"Tier 8",note:"Late-round WR depth."},
  {rank:118,marketRank:118,player:"Bo Nix",team:"DEN",pos:"QB",tag:"TARGET QB",tier:"Tier 8",note:"Scout likes the late-round QB price."},
  {rank:119,marketRank:119,player:"Rachaad White",team:"WAS",pos:"RB",tag:"DEPTH",tier:"Tier 8",note:"Bench RB depth."},
  {rank:120,marketRank:120,player:"Jakobi Meyers",team:"JAX",pos:"WR",tag:"VALUE",tier:"Tier 8",note:"Useful late WR value."},
  {rank:121,marketRank:121,player:"Brock Purdy",team:"SF",pos:"QB",tag:"TARGET QB",tier:"Tier 9",note:"Strong wait-on-QB target."},
  {rank:122,marketRank:122,player:"Mark Andrews",team:"BAL",pos:"TE",tag:"VALUE",tier:"Tier 9",note:"Veteran TE value if he slides."},
  {rank:123,marketRank:123,player:"Matthew Golden",team:"GB",pos:"WR",tag:"UPSIDE",tier:"Tier 9",note:"Bench WR upside."},
  {rank:124,marketRank:124,player:"Denver Broncos D/ST",team:"DEN",pos:"DEF",tag:"DST TARGET",tier:"DST Tier 1",specialRank:2,note:"Top-tier D/ST; final-round target."},
  {rank:125,marketRank:125,player:"De'Zhaun Stribling",team:"SF",pos:"WR",tag:"UPSIDE",tier:"Tier 9",note:"Deep WR swing."},
  {rank:126,marketRank:126,player:"Dallas Goedert",team:"PHI",pos:"TE",tag:"VALUE",tier:"Tier 9",note:"Late TE floor."},
  {rank:127,marketRank:127,player:"Xavier Worthy",team:"KC",pos:"WR",tag:"UPSIDE",tier:"Tier 9",note:"Big-play bench ceiling."},
  {rank:128,marketRank:128,player:"Romeo Doubs",team:"NE",pos:"WR",tag:"DEPTH",tier:"Tier 9",note:"Late WR depth."},
  {rank:129,marketRank:129,player:"Chris Rodriguez",team:"JAX",pos:"RB",tag:"UPSIDE",tier:"Tier 9",note:"Bench RB swing."},
  {rank:130,marketRank:130,player:"Philadelphia Eagles D/ST",team:"PHI",pos:"DEF",tag:"DST TARGET",tier:"DST Tier 2",specialRank:5,note:"Strong D/ST; wait until the end."},
  {rank:131,marketRank:131,player:"Deebo Samuel",team:"SF",pos:"WR",tag:"DEPTH",tier:"Tier 9",note:"Veteran WR depth."},
  {rank:132,marketRank:132,player:"Tyler Allgeier",team:"ARI",pos:"RB",tag:"UPSIDE",tier:"Tier 9",note:"Contingent RB upside."},
  {rank:133,marketRank:133,player:"Tyrone Tracy",team:"NYG",pos:"RB",tag:"UPSIDE",tier:"Tier 9",note:"Late RB depth."},
  {rank:134,marketRank:134,player:"Baltimore Ravens D/ST",team:"BAL",pos:"DEF",tag:"DST VALUE",tier:"DST Tier 3",specialRank:11,note:"Talent remains, but Scout ranks other D/STs higher."},
  {rank:135,marketRank:135,player:"Brandon Aubrey",team:"DAL",pos:"K",tag:"K TARGET",tier:"K Tier 1",specialRank:1,note:"Scout's top kicker; only take him at the end."},
  {rank:136,marketRank:136,player:"Cameron Dicker",team:"LAC",pos:"K",tag:"K TARGET",tier:"K Tier 1",specialRank:3,note:"Top-tier kicker; final-round target."},
  {rank:137,marketRank:137,player:"Jason Myers",team:"SEA",pos:"K",tag:"K TARGET",tier:"K Tier 1",specialRank:4,note:"Top-tier kicker; final-round target."},
  {rank:138,marketRank:138,player:"Ka'imi Fairbairn",team:"HOU",pos:"K",tag:"K TARGET",tier:"K Tier 1",specialRank:2,note:"Top-tier kicker; final-round target."},
  {rank:139,marketRank:139,player:"Zach Charbonnet",team:"SEA",pos:"RB",tag:"UPSIDE",tier:"Tier 9",note:"Late RB contingent upside."},
  {rank:140,marketRank:140,player:"Jared Goff",team:"DET",pos:"QB",tag:"LATE QB",tier:"Tier 9",note:"Useful late QB if the room waits."},
  {rank:141,marketRank:141,player:"Woody Marks",team:"HOU",pos:"RB",tag:"UPSIDE",tier:"Tier 10",note:"Late RB upside."},
  {rank:142,marketRank:142,player:"Cam Little",team:"JAX",pos:"K",tag:"K TARGET",tier:"K Tier 1",specialRank:5,note:"Top-five kicker; final-round target."},
  {rank:143,marketRank:143,player:"Jalen Coker",team:"CAR",pos:"WR",tag:"UPSIDE",tier:"Tier 10",note:"Deep WR swing."},
  {rank:144,marketRank:144,player:"Jonah Coleman",team:"DEN",pos:"RB",tag:"UPSIDE",tier:"Tier 10",note:"Late RB swing."},
  {rank:145,marketRank:145,player:"Kyler Murray",team:"MIN",pos:"QB",tag:"TARGET QB",tier:"Tier 10",note:"Rushing floor makes him an appealing deep QB."},
  {rank:146,marketRank:146,player:"Khalil Shakir",team:"BUF",pos:"WR",tag:"VALUE",tier:"Tier 10",note:"Late WR depth."},
  {rank:147,marketRank:147,player:"Oronde Gadsden",team:"LAC",pos:"TE",tag:"UPSIDE",tier:"Tier 10",note:"Deep TE upside."},
  {rank:148,marketRank:148,player:"Rashid Shaheed",team:"SEA",pos:"WR",tag:"UPSIDE",tier:"Tier 10",note:"Big-play late WR."},
  {rank:149,marketRank:149,player:"Hunter Henry",team:"NE",pos:"TE",tag:"DEPTH",tier:"Tier 10",note:"Late TE floor."},
  {rank:150,marketRank:150,player:"New England Patriots D/ST",team:"NE",pos:"DEF",tag:"DST VALUE",tier:"DST Tier 2",specialRank:6,note:"Strong D/ST option at the end."},
  {rank:151,marketRank:151,player:"Jake Bates",team:"DET",pos:"K",tag:"K VALUE",tier:"K Tier 2",specialRank:9,note:"Solid late kicker."},
  {rank:152,marketRank:152,player:"Baker Mayfield",team:"TB",pos:"QB",tag:"LATE QB",tier:"Tier 10",note:"Deep one-QB option."},
  {rank:153,marketRank:153,player:"Minnesota Vikings D/ST",team:"MIN",pos:"DEF",tag:"DST VALUE",tier:"DST Tier 2",specialRank:8,note:"Good late D/ST option."},
  {rank:154,marketRank:154,player:"Alvin Kamara",team:"NO",pos:"RB",tag:"MONITOR",tier:"Tier 10",note:"Late veteran RB depth; monitor health/role."},
  {rank:155,marketRank:155,player:"Jacksonville Jaguars D/ST",team:"JAX",pos:"DEF",tag:"DST VALUE",tier:"DST Tier 3",specialRank:9,note:"Streamable D/ST with upside."},
  {rank:156,marketRank:156,player:"Harrison Mevis",team:"LAR",pos:"K",tag:"K VALUE",tier:"K Tier 3",specialRank:12,note:"Late kicker option."},
  {rank:157,marketRank:157,player:"Brenton Strange",team:"JAX",pos:"TE",tag:"DEPTH",tier:"Tier 10",note:"Deep TE option."},
  {rank:158,marketRank:158,player:"Denzel Boston",team:"CLE",pos:"WR",tag:"UPSIDE",tier:"Tier 10",note:"Deep WR swing."},
  {rank:159,marketRank:159,player:"Mike Washington",team:"LV",pos:"RB",tag:"UPSIDE",tier:"Tier 10",note:"Late RB lottery ticket."},
  {rank:160,marketRank:160,player:"Evan McPherson",team:"CIN",pos:"K",tag:"K VALUE",tier:"K Tier 2",specialRank:8,note:"Solid kicker at the end."},
  {rank:161,marketRank:161,player:"Ja'Kobi Lane",team:"BAL",pos:"WR",tag:"UPSIDE",tier:"Tier 10",note:"Deep WR swing."},
  {rank:162,marketRank:162,player:"Los Angeles Chargers D/ST",team:"LAC",pos:"DEF",tag:"DST VALUE",tier:"DST Tier 3",specialRank:10,note:"Late-round D/ST option."},
  {rank:163,marketRank:163,player:"Keaton Mitchell",team:"LAC",pos:"RB",tag:"UPSIDE",tier:"Tier 10",note:"Deep RB speed/upside."},
  {rank:164,marketRank:164,player:"Will Reichard",team:"MIN",pos:"K",tag:"K VALUE",tier:"K Tier 3",specialRank:16,note:"Deep kicker option."},
  {rank:165,marketRank:165,player:"Tank Bigsby",team:"PHI",pos:"RB",tag:"UPSIDE",tier:"Tier 10",note:"Late RB contingent upside."},
  {rank:166,marketRank:166,player:"Jalen Nailor",team:"LV",pos:"WR",tag:"UPSIDE",tier:"Tier 10",note:"Deep WR option."},
  {rank:167,marketRank:167,player:"Jordan Love",team:"GB",pos:"QB",tag:"LATE QB",tier:"Tier 10",note:"Deep QB option."},
  {rank:168,marketRank:168,player:"Pittsburgh Steelers D/ST",team:"PIT",pos:"DEF",tag:"DST VALUE",tier:"DST Tier 2",specialRank:7,note:"Scout likes the talent; draft late."},
  {rank:169,marketRank:169,player:"Sam Darnold",team:"SEA",pos:"QB",tag:"LATE QB",tier:"Tier 10",note:"Deep QB option."},
  {rank:170,marketRank:170,player:"Tyjae Spears",team:"TEN",pos:"RB",tag:"UPSIDE",tier:"Tier 10",note:"Late RB depth."},
  {rank:171,marketRank:171,player:"Isiah Pacheco",team:"DET",pos:"RB",tag:"UPSIDE",tier:"Tier 10",note:"Late RB lottery ticket."},
  {rank:172,marketRank:172,player:"Brian Robinson",team:"ATL",pos:"RB",tag:"DEPTH",tier:"Tier 10",note:"Late RB depth."},
  {rank:173,marketRank:173,player:"Eddy Pineiro",team:"SF",pos:"K",tag:"K VALUE",tier:"K Tier 2",specialRank:6,note:"Top-10 kicker target at the end."},
  {rank:174,marketRank:174,player:"Kenyon Sadiq",team:"NYJ",pos:"TE",tag:"UPSIDE",tier:"Tier 10",note:"Deep TE swing."}
];
window.DEEP_DRAFT_UPDATED = "August 28, 2026";
